# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0002_drink_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
