# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 13:32
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0003_auto_20160112_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
