# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0005_auto_20160112_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
