# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2022-09-29 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0006_auto_20160112_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='photo',
            field=models.ImageField(default='static/uploads/canette.jpg', upload_to='static/uploads/'),
        ),
    ]
