# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2022-09-29 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0007_auto_20211011_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(verbose_name="Date d'alimentation du stock"),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantite actuelle'),
        ),
    ]
