# Generated by Django 3.2.8 on 2021-10-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0008_alter_drink_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='ean13',
            field=models.CharField(default='', max_length=40),
        ),
    ]
