# Generated by Django 3.2.8 on 2021-10-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0009_drink_ean13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
