# Generated by Django 3.2.8 on 2021-10-15 08:14

from django.db import migrations
import drink.models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0012_auto_20211012_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=jsonfield.fields.JSONField(blank=True, null=True, validators=[drink.models.validate_openff]),
        ),
    ]
